substitutions:
  device_name: hcq-system-simulator
  friendly_name: HCQ Boiler and Quatt ODU Simulator
  odu_1_address: "1"
  odu_2_address: "2"

packages:
  boiler: !include hcq_v1_boiler_simulator.yaml
  quatt_odu: !include packages/quatt_odu_simulator.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  build_path: build/hcq_v1_system_simulator

wifi:
  ap:
    ssid: "HCQ System Simulator"
