// Generated by scripts/generate_odu_contract.py. Do not edit.
#pragma once

#include <array>
#include <cstdint>

namespace esphome::quatt_odu_simulator {

enum class Access : uint8_t { READ = 1, WRITE = 2, READ_WRITE = 3 };
enum class Confidence : uint8_t { OBSERVED, DOCUMENTED, CONTROLLER_CONTRACT, SYNTHETIC, UNKNOWN };

struct RegisterDescriptor {
  uint16_t address;
  uint8_t width_words;
  const char *name;
  Access access;
  float scale;
  float offset;
  uint8_t profile_mask;
  Confidence confidence;
  bool reserved;
};

struct RegisterRangeDescriptor {
  uint16_t start;
  uint16_t end;
  const char *name;
  Access access;
  uint8_t profile_mask;
  Confidence confidence;
};

inline constexpr std::array<RegisterDescriptor, 53> REGISTER_DESCRIPTORS = {{
    {1999U, 1U, "compressor_level", Access::READ_WRITE, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2006U, 1U, "silent_mode", Access::READ_WRITE, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2010U, 1U, "pump_mode", Access::READ_WRITE, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2015U, 1U, "pump_speed_ipwm", Access::READ_WRITE, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2099U, 1U, "active_working_mode", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2100U, 1U, "ac_voltage", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2101U, 1U, "ac_current", Access::READ, 0.1f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2102U, 1U, "compressor_frequency_demand", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::OBSERVED, false},
    {2103U, 1U, "compressor_frequency", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::OBSERVED, false},
    {2104U, 1U, "fan_speed_max", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2105U, 1U, "fan_speed", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2106U, 1U, "reserved_2106", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, true},
    {2107U, 1U, "eev_position", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2108U, 1U, "operating_status", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2109U, 1U, "reserved_2109", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, true},
    {2110U, 1U, "outside_temperature", Access::READ, 0.01f, -30.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2111U, 1U, "evaporator_coil_temperature", Access::READ, 0.01f, -30.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2112U, 1U, "gas_discharge_temperature", Access::READ, 0.01f, -30.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2113U, 1U, "gas_return_temperature", Access::READ, 0.01f, -30.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2114U, 1U, "compressor_code", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::OBSERVED, false},
    {2115U, 1U, "flow_switch_status", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2116U, 1U, "evaporator_pressure", Access::READ, 0.1f, 0.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2117U, 1U, "condenser_pressure", Access::READ, 0.1f, 0.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2118U, 1U, "defrost", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2119U, 1U, "protection_fault_word_1", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2120U, 1U, "fault_word_2", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2121U, 1U, "fault_word_3", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2122U, 1U, "pcb_program", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::OBSERVED, false},
    {2123U, 1U, "eeprom_metadata_2123", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2124U, 1U, "eeprom_metadata_2124", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2125U, 1U, "firmware_metadata_2125", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2126U, 1U, "firmware_metadata_2126", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2127U, 1U, "control_board_item", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::OBSERVED, false},
    {2128U, 1U, "reserved_2128", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, true},
    {2129U, 1U, "reserved_2129", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, true},
    {2130U, 1U, "reserved_2130", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, true},
    {2131U, 1U, "condensing_temperature", Access::READ, 0.01f, -30.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2132U, 1U, "evaporating_temperature", Access::READ, 0.01f, -30.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2133U, 1U, "water_in_temperature", Access::READ, 0.01f, -30.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2134U, 1U, "water_out_temperature", Access::READ, 0.01f, -30.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2135U, 1U, "inner_coil_temperature", Access::READ, 0.01f, -30.0f, 0x1EU, Confidence::SYNTHETIC, false},
    {2136U, 1U, "reserved_2136", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, true},
    {2137U, 1U, "pump_ipwm_feedback", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {2138U, 1U, "water_flow", Access::READ, 0.618f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {3999U, 1U, "requested_working_mode", Access::READ_WRITE, 1.0f, 0.0f, 0x1EU, Confidence::CONTROLLER_CONTRACT, false},
    {11004U, 1U, "extended_metadata_11004", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, false},
    {11005U, 1U, "extended_metadata_11005", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, false},
    {11006U, 1U, "extended_metadata_11006", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, false},
    {11007U, 1U, "extended_metadata_11007", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, false},
    {11008U, 1U, "extended_metadata_11008", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, false},
    {11009U, 1U, "extended_metadata_11009", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::UNKNOWN, false},
    {11160U, 1U, "customer_model_word_0", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::OBSERVED, false},
    {11161U, 1U, "customer_model_word_1", Access::READ, 1.0f, 0.0f, 0x1EU, Confidence::OBSERVED, false},
}};

inline constexpr std::array<RegisterRangeDescriptor, 6> REGISTER_RANGE_DESCRIPTORS = {{
    {2999U, 3510U, "eeprom_fixture", Access::READ, 0x1EU, Confidence::UNKNOWN},
    {3000U, 3021U, "base_frequency_table", Access::READ_WRITE, 0x1EU, Confidence::OBSERVED},
    {3050U, 3069U, "v2_frequency_extension", Access::READ_WRITE, 0x10U, Confidence::CONTROLLER_CONTRACT},
    {11120U, 11139U, "model_text", Access::READ, 0x1EU, Confidence::SYNTHETIC},
    {11160U, 11179U, "customer_model_text", Access::READ, 0x1EU, Confidence::SYNTHETIC},
    {11219U, 11238U, "serial_number_text", Access::READ, 0x1EU, Confidence::SYNTHETIC},
}};

inline constexpr bool access_readable(Access access) {
  return access == Access::READ || access == Access::READ_WRITE;
}
inline constexpr bool access_writable(Access access) {
  return access == Access::WRITE || access == Access::READ_WRITE;
}

}  // namespace esphome::quatt_odu_simulator
