// Generated by scripts/generate_odu_contract.py. Do not edit.
#pragma once

#include <array>

namespace esphome::quatt_odu_simulator {

struct PerformanceGrid {
  std::array<float, 10> frequency_hz;
  std::array<float, 2> ambient_c;
  std::array<float, 2> supply_c;
  const float *thermal_power_w;
  const float *cop;
};

inline constexpr std::array<float, 40> V1_THERMAL_POWER_W = {1675.91f, 2171.97f, 2736.4f, 3081.76f, 3432.15f, 3787.56f, 4087.58f, 4513.47f, 4883.97f, 5196.55f, 1465.62f, 1973.0f, 2550.02f, 2902.94f, 3260.88f, 3623.85f, 3930.16f, 4364.86f, 4742.91f, 5061.78f, 2071.03f, 2635.97f, 3276.94f, 3668.23f, 4064.54f, 4465.88f, 4804.17f, 5283.63f, 5700.05f, 6050.91f, 1811.21f, 2387.48f, 3041.04f, 3439.87f, 3843.74f, 4252.63f, 4597.21f, 5085.49f, 5509.46f, 5866.61f};
inline constexpr std::array<float, 40> V1_COP = {3.96f, 4.04f, 4.08f, 4.07f, 4.04f, 3.99f, 3.94f, 3.83f, 3.71f, 3.6f, 2.82f, 2.98f, 3.11f, 3.16f, 3.18f, 3.19f, 3.17f, 3.13f, 3.06f, 2.99f, 4.71f, 4.76f, 4.75f, 4.72f, 4.67f, 4.6f, 4.52f, 4.39f, 4.25f, 4.11f, 3.45f, 3.58f, 3.67f, 3.69f, 3.7f, 3.68f, 3.64f, 3.57f, 3.48f, 3.39f};
inline constexpr PerformanceGrid V1_GRID = {{30, 39, 49, 55, 61, 67, 72, 79, 85, 90}, {2, 7}, {35, 45}, V1_THERMAL_POWER_W.data(), V1_COP.data()};
inline constexpr std::array<float, 40> V2_THERMAL_POWER_W = {3238.45f, 3755.7f, 4272.94f, 4617.77f, 4790.19f, 5135.02f, 5479.85f, 5910.88f, 6341.92f, 6772.96f, 2462.83f, 2934.41f, 3406.0f, 3720.4f, 3877.59f, 4191.99f, 4506.38f, 4899.37f, 5292.36f, 5685.35f, 4147.38f, 4799.95f, 5452.52f, 5887.57f, 6105.1f, 6540.15f, 6974.76f, 7518.54f, 8062.32f, 8606.1f, 3396.36f, 4003.28f, 4610.2f, 5014.82f, 5217.12f, 5621.74f, 6025.9f, 6531.64f, 7037.37f, 7543.1f};
inline constexpr std::array<float, 40> V2_COP = {3.97f, 3.63f, 3.29f, 3.06f, 2.95f, 2.72f, 2.5f, 2.22f, 1.93f, 1.65f, 2.57f, 2.5f, 2.44f, 2.4f, 2.37f, 2.33f, 2.29f, 2.23f, 2.18f, 2.12f, 12.21f, 11.46f, 10.73f, 10.23f, 9.98f, 9.49f, 9.0f, 8.38f, 7.76f, 7.15f, 9.35f, 8.88f, 8.41f, 8.11f, 7.95f, 7.64f, 7.33f, 6.94f, 6.55f, 6.16f};
inline constexpr PerformanceGrid V2_GRID = {{20, 26, 30, 48, 55, 61, 72, 80, 85, 90}, {-10, 11}, {35, 45}, V2_THERMAL_POWER_W.data(), V2_COP.data()};

}  // namespace esphome::quatt_odu_simulator
