// Generated by scripts/generate_odu_contract.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace esphome::quatt_odu_simulator {

enum class Profile : uint8_t { DISABLED = 0, V1, V1_5, V2_OLD, V2_NEW };

struct ProfileDefinition {
  Profile profile;
  const char *label;
  bool enabled;
  uint8_t max_physical_level;
  uint16_t compressor_code;
  uint16_t pcb_program;
  uint16_t control_board_item;
  std::array<uint16_t, 2> customer_model_words;
  std::array<uint8_t, 21> factory_cooling;
  std::array<uint8_t, 21> factory_heating;
};

struct RuntimePresetDefinition {
  Profile profile;
  const char *id;
  const char *label;
  std::array<uint8_t, 21> cooling;
  std::array<uint8_t, 21> heating;
};

inline constexpr std::array<ProfileDefinition, 5> PROFILE_DEFINITIONS = {{
    {Profile::DISABLED, "Disabled", false, 0U, 0U, 0x0000U, 0x0000U, {0x0000U, 0x0000U}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {Profile::V1, "V1", true, 10U, 0U, 0x0119U, 0x0037U, {0x0000U, 0x0000U}, {0, 30, 36, 42, 47, 52, 56, 61, 66, 71, 74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 30, 39, 49, 55, 61, 67, 72, 79, 85, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {Profile::V1_5, "V1.5", true, 10U, 0U, 0x011EU, 0x0E37U, {0x0000U, 0x0000U}, {0, 30, 36, 42, 47, 52, 56, 61, 66, 71, 74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 30, 39, 49, 55, 61, 67, 72, 79, 85, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {Profile::V2_OLD, "V2 old model", true, 10U, 2825U, 0x0122U, 0x0E37U, {0x414DU, 0x4836U}, {0, 30, 36, 42, 46, 48, 52, 56, 61, 66, 71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 20, 26, 30, 48, 55, 61, 72, 80, 85, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {Profile::V2_NEW, "V2 new model", true, 20U, 2825U, 0x0201U, 0x1037U, {0x414DU, 0x4836U}, {0, 20, 26, 30, 34, 36, 38, 40, 42, 44, 46, 48, 52, 54, 56, 58, 60, 64, 66, 68, 71}, {0, 20, 26, 30, 36, 40, 45, 48, 52, 55, 60, 65, 68, 72, 76, 82, 85, 90, 95, 102, 110}},
}};

inline constexpr std::array<RuntimePresetDefinition, 2> RUNTIME_PRESETS = {{
    {Profile::V1, "v1_runtime_modified", "V1 runtime modified", {0, 20, 22, 24, 26, 28, 30, 30, 30, 30, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 30, 39, 49, 55, 61, 67, 72, 79, 85, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {Profile::V1_5, "v1_5_runtime_modified", "V1.5 runtime modified", {0, 26, 28, 30, 32, 34, 36, 38, 40, 71, 74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 30, 39, 49, 55, 61, 67, 72, 79, 85, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
}};

inline constexpr std::array<uint16_t, 10> LEGACY_HEATING_EXTENSION = {0xA501U, 0xA502U, 0xA503U, 0xA504U, 0xA505U, 0xA506U, 0xA507U, 0xA508U, 0xA509U, 0xA50AU};
inline constexpr std::array<uint16_t, 10> LEGACY_COOLING_EXTENSION = {0xC501U, 0xC502U, 0xC503U, 0xC504U, 0xC505U, 0xC506U, 0xC507U, 0xC508U, 0xC509U, 0xC50AU};

inline constexpr const ProfileDefinition &profile_definition(Profile profile) {
  const size_t index = static_cast<size_t>(profile);
  return PROFILE_DEFINITIONS[index < PROFILE_DEFINITIONS.size() ? index : 0U];
}

inline constexpr Profile detect_profile(uint16_t compressor_code, uint16_t pcb_program, uint16_t control_board_item) {
  for (const auto &definition : PROFILE_DEFINITIONS)
    if (definition.enabled && definition.compressor_code == compressor_code &&
        definition.pcb_program == pcb_program && definition.control_board_item == control_board_item)
      return definition.profile;
  return Profile::DISABLED;
}

inline constexpr const RuntimePresetDefinition *runtime_modified_preset(Profile profile) {
  for (const auto &preset : RUNTIME_PRESETS)
    if (preset.profile == profile) return &preset;
  return nullptr;
}

}  // namespace esphome::quatt_odu_simulator
